/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kt.gitpod.parser

import com.charleskorn.kaml.Yaml
import net.pwall.json.schema.codegen.CodeGenerator
import java.io.File
import java.io.BufferedReader

//@Serializable
//data class Team(
//        val leader: String,
//        val members: List<String>
//)

//val input = """
//        leader: Amy
//        members:
//          - Bob
//          - Cindy
//          - Dan
//    """.trimIndent()

fun main() {
    println("Generating classes")
//    try {
//        val codeGenerator = CodeGenerator()
//        codeGenerator.baseDirectoryName = "/workspace/kt-gitpod-parser/app/src/main/kotlin"
//        codeGenerator.basePackageName = "kt.gitpod.parser"
//        codeGenerator.generate(File("/workspace/kt-gitpod-parser/gitpod-schema.json"))
//        println("Classes generated")
//    } catch (t: Throwable) {
//        throw t
//    }

    val bufferedReader: BufferedReader = File("/workspace/kt-gitpod-parser/.gitpod.yml").bufferedReader()
    val input = bufferedReader.use { it.readText() }
    val result = Yaml.default.decodeFromString(GitpodConfig.serializer(), input)
//

    println(result.jetbrains)
}
